// pages
export 'auth/pages/forgot_password_page.dart';
export 'auth/pages/login_page.dart';
export 'auth/pages/register_page.dart';
export 'feeds/feeds_page.dart';
export 'search/search_page.dart';
export 'settings/settings_page.dart';
export 'profile/edit_profile_page.dart';
export 'profile/user_profile_page.dart';
export 'post/post_page.dart';
export 'notifications/notifications_page.dart';
